// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qioziympooutguqugfju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpb3ppeW1wb291dGd1cXVnZmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NzIwNzQsImV4cCI6MjA1ODI0ODA3NH0.JoPPvG5BhWa1kgCJ5asyIwLkQfvltNhzJhbA5V5edgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);